function expectations=chipDynoStatPostEst(data,x,Sigma,beta,gamma,mu);

% CHIPDYNOPOSTEST computes posterior expectations 

% CHIPDYNO

npts=size(data,2);
nTrans=size(x,1);
invC=chipStatMatrixInverter(Sigma, gamma, beta,x,npts);
Y=Sigma*x;
lambda=Y'*x;
factor=cos(gamma)^2;
coeff=x'*mu';
YYT=Y*Y';
invSigma=pdinv(Sigma);
%Z=invSigma*mu';
Mean=[beta^2*sum(data.*(invC.Sigma(1,:)+lambda*invC.YYT(1,:)))*Y'+ ...
      (1+factor)^-1*(invC.Sigma(1,1)*mu+coeff*invC.YYT(1,1)*Y')+ ...
     (1-factor)*(1+factor)^-1*(sum(invC.Sigma(1,2:end-1))*mu+coeff* ...
        sum(invC.YYT(1,2:end-1))*Y')+(1+factor)^-1*(invC.Sigma(1, ...
                                                  end)*mu+coeff* ...
     invC.YYT(1,end)*Y')];

for i=2:npts-1

  Mean=[Mean;beta^2*sum(data.*(invC.Sigma(i,:)+lambda*invC.YYT(i,:)))*Y'+ ...
        (1+factor)^-1*(invC.Sigma(i,1)*mu+coeff*invC.YYT(i,1)*Y')+ ...
     (1-factor)*(1+factor)^-1*(sum(invC.Sigma(i,2:end-1))*mu+coeff* ...
        sum(invC.YYT(i,2:end-1))*Y')+(1+factor)^-1*(invC.Sigma(i, ...
                                                  end)*mu+coeff* ...
     invC.YYT(i,end)*Y')];
end
Mean=[Mean;beta^2*sum(data.*(invC.Sigma(end,:)+lambda*invC.YYT(end,:)))*Y'+ ...
      (1+factor)^-1*(invC.Sigma(end,1)*mu+coeff*invC.YYT(end,1)*Y')+ ...
     (1-factor)*(1+factor)^-1*(sum(invC.Sigma(end,2:end-1))*mu+coeff* ...
        sum(invC.YYT(end,2:end-1))*Y')+(1+factor)^-1*(invC.Sigma(end, ...
                                                  end)*mu+coeff* ...
     invC.YYT(end,end)*Y')];
        
       
expectations.b=Mean;
expectations.bTb=[];
for i=1:npts
  expectations.bTb=[expectations.bTb;invC.Sigma(i,i)*diag(Sigma)'+ ...
                    invC.YYT(i,i)*Y'.*Y'];
end


  
     
     